[package]
   name = "serdepp"
   version = "0.1.0"
   description = "c++ universal serialize deserialize library like rust serde"
   #tool-version = "dev"

[lib]
   name = "serdepp"
   #type = "static"
   #source= ["src/to_static.cpp"]
   type = "header-only"


[[example]]
    name = "serde_example1"
    source = ["examples/example1.cpp"]

[[example]]
    name = "serde_example"
    source = ["examples/example.cpp"]

[[example]]
    name = "simple_example"
    source = ["examples/simple_example.cpp"]

[[example]]
    name = "benchmark"
    source = ["benchmark/benchmark.cpp"]

[dependencies]
    fmt = {version="7.1.3", link="public"}
    nameof = { version="0.10.0", link="public"}
    magic_enum = { version= "0.7.3", link="public"}
    yaml-cpp   = { version="0.6.3",  link="public", optional=true}
    toml11     = { version="3.7.0",  link="public", optional=true}
    nlohmann_json = { version="3.9.1", link="public", optional=true}
    benchmark = { version="1.5.2", optional=true}

#[dev-dependencies]
#    benchmark = {version="1.5.2", optional=true}
