[package]
   name = "serdepp"
   version = "0.0.2"
   description = "c++ universal serialize deserialize library like rust serde"

[lib]
   name = "serdepp"
   type = "static"
   source= ["src/to_static.cpp"]

[[bin]]
    name = "serde_test"
    source = ["test/test.cpp"]


#[[example]]
#    name = "nlohmann_json_example"
#    source = ["examples/nlohmann_json_example.cpp"]
#
#[[example]]
#    name = "toml11_example"
#    source = ["examples/toml11_example.cpp"]
#
#[[example]]
#    name = "convert_example"
#    source = ["examples/convert_example.cpp"]
#
#[[example]]
#    name = "test_all"
#    source = ["examples/variant_test.cpp"]
#
#[[example]]
#    name = "overwrite"
#    source = ["examples/overwrite.cpp"]
#
#[[example]]
#    name = "benchmark"
#    source = ["benchmark/benchmark.cpp"]

#[[bin]]
#    name = "yaml-cpp_example"
#    source = ["examples/yaml-cpp_example.cpp"]

#[[example]]
#    name = "tomlpp_example"
#    source = ["examples/tomlpp_example.cpp"]

[dependencies]
    fmt = "7.1.3"
    toml11= {version="3.6.0"}
    nlohmann_json= {version="3.9.1"}
    #benchmark="1.5.2"

[dev-dependencies]
#    tomlpp="git"
    yaml-cpp= {version="0.6.3", optional=true}
    benchmark={version="1.5.2", optional=true}
