[package]
   name = "serdepp"
   version = "0.1.0"
   description = "c++ universal serialize deserialize library like rust serde"

[lib]
   name = "serdepp"
   type = "static"
   source= ["src/to_static.cpp"]

[[example]]
    name = "serde_example"
    source = ["examples/example.cpp"]

[[example]]
    name = "simple_example"
    source = ["examples/simple_example.cpp"]

[[benchmark]]
    name = "benchmark"
    source = ["benchmark/benchmark.cpp"]


[dependencies]
    fmt = "7.1.3"
    nameof = "0.10.0"
    magic_enum = "0.7.3"
    yaml-cpp  = {version="0.6.3", optional=true}
    toml11    = {version="3.6.0", optional=true}
    nlohmann_json = {version="3.9.1", optional=true}

[dev-dependencies]
    benchmark = {version="1.5.2", optional=true}
