[package]
   name = "serdepp"
   version = "0.0.1"
   description = "c++ universal serialize deserialize library like rust serde"

[lib]
   name = "serdepp"
   type = "header-only"

[[bin]]
    name = "nlohmann_json_example"
    source = ["examples/nlohmann_json_example.cpp"]

[[bin]]
    name = "tomlpp_example"
    source = ["examples/tomlpp_example.cpp"]

[dependencies]
    fmt = "7.0.3"

[dev-dependencies]
    nlohmann_json="3.9.1"
    tomlpp="git"
    yaml-cpp="0.6.3"
