name: Linux

on: [push]

jobs:
  ubuntu-bionic-gcc-11:
    runs-on: ubuntu-18.04
    env:
      CMAKE_FLAGS: '-DUSE_CPPM_PATH=ON -DSERDEPP_USE_NLOHMANN_JSON=ON -DSERDEPP_USE_TOML11=ON -DSERDEPP_USE_YAML-CPP=ON -DSERDEPP_BUILD_EXAMPLES=ON -DSERDEPP_USE_BENCHMARK=ON'
    strategy:
      matrix:
        build-type: ['Release', 'Debug']
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -yq g++-11 gcc-11 libc++-dev libc++abi-dev build-essential libstdc++-11-dev
    - name: Compiler Setting
      run: |
        echo "CC=gcc-11" >> $GITHUB_ENV
        echo "CXX=g++-11" >> $GITHUB_ENV
    - name: CMake build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build-type}} $CMAKE_FLAGS .
        cd build
        cmake --build . --config ${{matrix.build-type}}
    - name: Run Test Script
      run: |
        cd ${{matrix.build-type}}
        ./serde_example
        ./serde_example1
        ./simple_example

  ubuntu-bionic-llvm-8:
    runs-on: ubuntu-18.04
    env:
      CMAKE_FLAGS: '-DUSE_CPPM_PATH=ON -DSERDEPP_USE_NLOHMANN_JSON=ON -DSERDEPP_USE_TOML11=ON -DSERDEPP_USE_YAML-CPP=ON -DSERDEPP_BUILD_EXAMPLES=ON -DSERDEPP_USE_BENCHMARK=ON'
    strategy:
      matrix:
        build-type: ['Release', 'Debug']
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo add-apt-repository -y "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
        sudo apt-get update
        sudo apt-get install -yq clang-8 libc++-dev libc++abi-dev libstdc++-8-dev build-essential
    - name: Compiler Setting
      run: |
        echo "CC=clang-8" >> $GITHUB_ENV
        echo "CXX=clang++-8" >> $GITHUB_ENV
    - name: CMake build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build-type}} $CMAKE_FLAGS .
        cd build
        cmake --build . --config ${{matrix.build-type}}
    - name: Run Test Script
      run: |
        cd ${{matrix.build-type}}
        ./serde_example
        ./serde_example1
        ./simple_example

