name: MacOS

on: [push]

jobs:
  macos-clang:
    runs-on: macos-latest
    env:
      CMAKE_FLAGS: '-DUSE_CPPM_PATH=ON -DSERDEPP_USE_NLOHMANN_JSON=ON -DSERDEPP_USE_TOML11=ON -DSERDEPP_USE_YAML-CPP=ON -DSERDEPP_BUILD_EXAMPLES=ON -DSERDEPP_USE_BENCHMARK=ON'
    strategy:
      matrix:
        build-type: ['Release', 'Debug']
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        brew install llvm cmake
    - name: Compiler Setting
      run: |
        echo "CC=/usr/local/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/usr/local/opt/llvm/bin/clang++" >> $GITHUB_ENV
    - name: CMake build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build-type}} $CMAKE_FLAGS .
        cd build
        cmake --build . --config ${{matrix.build-type}}
    - name: Run Test Script
      run: |
        cd ${{matrix.build-type}}
        ./serde_example
        ./serde_example1
        ./simple_example


  #  runs-on: macos-latest
  #  strategy:
  #    matrix:
  #      c-compiler: [gcc, clang]
  #      cxx-compiler: [g++, clang++]
  #  steps:
  #  - name: Clone Repository
  #    uses: actions/checkout@master
  #  - name: Compiler Setting
  #    run: echo Compiler Setting
  #    env:
  #      CC: ${{matrix.compiler}}
  #  - name: CMake build
  #    run: cmake -Bbuild . && cd build && cmake --build .
  #  - name: Cppm build install
  #    run: cd build && ./cppm build install
