name: Windows

on: [pull_request]

jobs:
  windows-msvc:
    runs-on: windows-2019
    env:
      CMAKE_FLAGS: '-DUSE_CPPM_PATH=ON -DSERDEPP_USE_NLOHMANN_JSON=ON -DSERDEPP_USE_TOML11=ON -DSERDEPP_USE_YAML-CPP=ON -DSERDEPP_BUILD_EXAMPLES=ON'
    strategy:
      matrix:
        build-type: ['Release', 'Debug']
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: CMake build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ${{env.CMAKE_FLAGS}}.
        cd build
        cmake --build . --config ${{matrix.build-type}}
    - name: Run Test Script
      run: |
        cd build/${{matrix.build-type}}
        ./serde_example
        ./serde_example1
        ./simple_example
